# Generated by Django 5.1.2 on 2024-11-11 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdpApp', '0002_alter_address_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
