# Generated by Django 5.1.2 on 2024-11-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdpApp', '0005_remove_blogdesc_category_id_remove_blog_blog_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
